name: web-CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install, build, and test
      run: |
        npm install
        npm run build:test --if-present
    - name: Docker Login
      uses: docker/build-push-action@v1
      with:
        registry: pekopeko
        username: ${{ DOCKER_USERNAME }}
        password: ${{ DOCKER_PASSWORD }}
        repository: czy0612/pekopeko
        tags: v1
